---
title: "Primates de Costa Rica"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r carga-paquetes, message=FALSE, echo=FALSE}
# Carga de paquetes 
library(dplyr)
library(ggplot2)
library(sf)
library(DT)
library(plotly)
library(leaflet)

```

```{r carga-datos, message=FALSE, echo=FALSE}
primates_cr <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/primates-cr-registros.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )

# Asignación de CRS
st_crs(primates_cr) = 4326

# Capa geespacial de cantones
cantones <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_cantones_simp_wgs84.geojson",
    quiet = TRUE
  )

```

```{r cruce-cartones, message=FALSE, echo=FALSE}
# Cruce espacial con la tabla de cantones, para obtener el nombre del cantón
primates_cr <- 
  primates_cr %>%
  st_join(cantones["canton"])
```

# Tablas de registros  
```{r Tabla-registro, message=FALSE, echo=FALSE}
# Tabla de registros de presencia
primates_cr %>%
  st_drop_geometry() %>%
  select(stateProvince, canton, family, species, eventDate) %>%
  datatable(
    colnames = c("Provincia", "Cantón", "Familia", "Especie", "Fecha"),
    options = list(
      searchHighlight = TRUE,
      language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json'),
      pageLength = 5
    )
  )
```

# Gráfico (Pastel)
```{r Gráfico-Pastel, message=FALSE, echo=FALSE}
fig <-
  plot_ly(
    labels = ~ c("Ateles geoffroyi", "Cebus capucinus", "Alouatta palliata", "Saimiri oerstedii"),
    values = ~ c(1994, 599, 453, 1463),
    type = 'pie') %>%
    config(locale = "es") %>% layout(
    title = 'Especies de Primates',
    
    xaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    ),
    
    yaxis = list(
      showgrid = FALSE,
      zeroline = FALSE,
      showticklabels = FALSE
    )
  )
    
fig
```

# Mapa de Distribución 

```{r message=FALSE, echo=FALSE}
primates_cr %>%
    select(stateProvince,
           canton,
           locality,
           eventDate,
           decimalLongitude,
           decimalLatitude) %>%
    leaflet() %>%
    addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
    addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
    addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
    addCircleMarkers(
      stroke = F,
      radius = 4,
      fillColor = 'gray',
      fillOpacity = 2,
      popup = paste(
        primates_cr$stateProvince,
        primates_cr$canton,
        primates_cr$locality,
        primates_cr$eventDate,
        primates_cr$decimalLongitude,
        primates_cr$decimalLatitude,
        sep = '<br/>'
      ),
      group = "Primates"
    ) %>%
    addLayersControl(
      baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI"),
      overlayGroups = c("Primates")
    ) %>%
    addMiniMap(
      tiles = providers$Stamen.OpenStreetMap.Mapnik,
      position = "bottomleft",
      toggleDisplay = TRUE
    )
```

